# Generated by Django 5.2.8 on 2025-11-26 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('ARTIGO', 'Artigo'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('descricao', models.TextField()),
                ('link_conteudo', models.URLField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('vagas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=20)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('horario', models.CharField(default='08h às 18h', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('PSICOLOGIA', 'Psicologia'), ('JURIDICO', 'Jurídico'), ('SOCIAL', 'Assistência Social')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_emergencia', models.TextField(default='Estou em perigo, por favor, ajude! Minha localização atual é...')),
                ('localizacao_automatica', models.BooleanField(default=False)),
                ('modo_disfarcado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('parentesco', models.CharField(max_length=50)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='rede_aura.planoseguranca')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.CharField(choices=[('RELATO', 'Relato'), ('MOTIVACAO', 'Motivação'), ('AJUDA', 'Pedido de Ajuda')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo Chamada')], default='VIDEO', max_length=20)),
                ('confirmado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_aura.profissional')),
            ],
        ),
    ]
