# Generated by Django 5.2.8 on 2025-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_aura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='conteudoeducativo',
            name='vagas',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='foto',
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='categoria',
            field=models.CharField(default='Direitos', max_length=50),
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='duracao',
            field=models.CharField(default='5 min', help_text='Ex: 5 min', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(default='VIDEO', max_length=20),
        ),
        migrations.AlterField(
            model_name='conteudoeducativo',
            name='link_conteudo',
            field=models.URLField(default='http://www.exemplo.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conteudoeducativo',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Vídeo'), ('ARTIGO', 'Artigo'), ('PODCAST', 'Podcast')], max_length=10),
        ),
    ]
