# Generated by Django 5.2.8 on 2025-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_aura', '0004_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoseguranca',
            name='data_aceite_termo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoseguranca',
            name='termo_aceito',
            field=models.BooleanField(default=False),
        ),
    ]
