# Generated by Django 5.2.8 on 2025-11-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_aura', '0007_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CasaAcolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('vagas_disponiveis', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DireitoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('TRABALHISTA', 'Trabalhista'), ('CIVIL', 'Civil'), ('PENAL', 'Penal')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_hora',
            field=models.DateTimeField(default='2025-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(default='2025-01-01 00:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='registro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_aura.areaatendimento'),
        ),
    ]
